# Train Test Split

## Import the relevant libraries

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [3]:
a = np.arange(1,101)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [6]:
train_test_split(a)

[array([ 58,  29,  23,  43,  20,  34,   3,  38,  71,  41,  72,  92,   1,
         75,  33,  78, 100,  31,  74,   9,  18,  24,  62,  11,  53,  94,
         47,   8,  27,  96,  16,  12,  44,  82,  35,  68,  26,  13,  73,
         55,  59,  10,  61,  65,  69,  25,  22,  88,  63,  56,  83,  45,
         79,  57,  70,  48,   4,  37,  17,  32,  28,   5,  81,  14,  77,
          6,  99,  98,  46,  49,  67,  50,   7,  40,  39]),
 array([93, 19, 89, 60, 21, 84, 54, 52, 42, 36, 64, 15, 86, 90, 95, 80, 87,
        85, 97, 66, 51, 76,  2, 30, 91])]

In [56]:
a_train, a_test, b_train, b_test = train_test_split(a,b ,test_size=0.2, random_state=366) #random_state refers to same shift after execution

## Explore the result

In [53]:
a_train.shape, a_test.shape

((80,), (20,))

In [54]:
a_train

array([ 64,  45,  91,  84,  87,  66,  31,  52,  14,  58,  11,  85,  13,
        90,  25,  12,  29,  69,  96,  37,  24,  46,  65,  63,  88,  76,
        49,  50,  62,  78,  39,  44,   9,  92,  48,  71,  94,  82,  89,
        73,   8,  81,  36,  98,  30,  54,  99, 100,  55,  15,  17,   4,
        20,  27,  47,  80,  19,  74,  38,  18,   7,  42,  79,  26,  95,
        41,  22,  51,   2,  33,  72,  75,   6,  32,  68,   1,   5,  35,
        59,  56])

In [55]:
a_test

array([16, 70, 77, 97, 57, 28, 10, 23, 86, 40, 34, 60, 67, 53,  3, 43, 93,
       21, 83, 61])

In [57]:
b_train.shape, b_test.shape

((80,), (20,))

In [58]:
b_train

array([564, 545, 591, 584, 587, 566, 531, 552, 514, 558, 511, 585, 513,
       590, 525, 512, 529, 569, 596, 537, 524, 546, 565, 563, 588, 576,
       549, 550, 562, 578, 539, 544, 509, 592, 548, 571, 594, 582, 589,
       573, 508, 581, 536, 598, 530, 554, 599, 600, 555, 515, 517, 504,
       520, 527, 547, 580, 519, 574, 538, 518, 507, 542, 579, 526, 595,
       541, 522, 551, 502, 533, 572, 575, 506, 532, 568, 501, 505, 535,
       559, 556])

In [59]:
b_test

array([516, 570, 577, 597, 557, 528, 510, 523, 586, 540, 534, 560, 567,
       553, 503, 543, 593, 521, 583, 561])