In [1]:
import numpy as np

# Addition

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

# Subtraction

In [5]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [6]:
m3

array([[ 5,  3],
       [-2,  4]])

In [7]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [8]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

# Adding vectors

In [9]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [10]:
v1 + v2

array([6, 6, 6, 6, 6])

In [11]:
v1 - v2

array([-4, -2,  0,  2,  4])

# Additions of Scalars

In [12]:
5 + 5

10

In [13]:
10 - 4

6

# Errors when adding

## Additions of Matrices

In [14]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [15]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [16]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Additions of vectors

In [17]:
v1 = np.array([1,2,3,4,5])

In [18]:
v1

array([1, 2, 3, 4, 5])

In [19]:
v3 = np.array([1,2,3])

In [20]:
v3

array([1, 2, 3])

In [21]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Exception (addition of Scalar)

In [22]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [23]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [24]:
v1

array([1, 2, 3, 4, 5])

In [25]:
v1 + 1

array([2, 3, 4, 5, 6])

In [26]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [27]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

## Transpose of Matrix

In [28]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [30]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

### Transposing Scalars

In [31]:
s = np.array([5])

In [32]:
s.T

array([5])

### Transposing Vectors

In [33]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [34]:
x.T

array([1, 2, 3])

In [35]:
x.shape

(3,)

In [36]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [37]:
x_reshaped.T

array([[1],
       [2],
       [3]])

# Dot Product

In [38]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [39]:
np.dot(x,y)

-66

## Scalar x Scalar

In [40]:
np.dot(5,6)

30

## Scalar x Vector

In [41]:
x

array([ 2,  8, -4])

In [42]:
5*x

array([ 10,  40, -20])

## Dot Product of Matrices

In [43]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [44]:
5*A

array([[ 25,  60,  30],
       [-15,   0,  70]])

### Matrix x Matrix

In [45]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [46]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])