# Import the relevant libraraies

In [1]:
import numpy as np

## Declaring scalars, vectors, matrices

In [25]:
s = 5

In [26]:
s

5

## Vectors

In [28]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices

In [9]:
m = np.array([[5,12,2],[-3,0,18]])
m

array([[ 5, 12,  2],
       [-3,  0, 18]])

## Data Types

In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)
s_array

array(5)

In [15]:
type(s_array)

numpy.ndarray

## Data Shapes

In [17]:
m.shape

(2, 3)

In [23]:
v.shape

(3,)

In [24]:
s_array.shape

()

## Creating a column Vector

In [21]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [22]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])